### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by rodowi**
Hopefully with this PR we will make all tests pass

Depends on #81

### CODE REVIEW

**Comment by zmully** [comment]
Rutroh. I think I accidentally committed a WIP branch to master? Let me back track later today to make sure your fixes are necessary.

**Comment by zmully** [comment]
See #81, I had a bad commit of a WIP branch to master.

**Comment by rodowi** [comment]
@zmully yea looks like a WIP got merged.

IMO would be good to see the fixes on a PR like this, instead of pushing revert commits directly to master.

**Comment by zmully** [comment]
@rodowi I'm not going to have time today to revert this, so if you want to do it, please go ahead. The commit I meant to merge was the lambda-cfn version update in package.json.

**Comment by rodowi** [comment]
@zmully lambda-cfn upgrade? the latest change in package.json is this https://github.com/mapbox/patrol-rules-aws/commit/a7e4182f6f1134afb7fe7abf07762fa077077895, but I can't find the WIP you mentioned here: https://github.com/mapbox/patrol-rules-aws/pull/82#issuecomment-224587611

what about `../lib/policyProcessor`? that file is missing in the repo and is invoked by two rules.

**Comment by zmully** [comment]
@rodowi  revert master to 2889d898bd43673ef21b9e0617b449b948926a78, then apply only the change to the package.json in a7e4182. Everything else is from a local branch I've not yet pushed.

**Comment by rodowi** [comment]
@zmully gotcha, I'll introduce that revert commit in this same branch so we leave a mark in the history about this PR.

**Comment by zmully** [comment]
Well, if I hadn't bungled the commit, this PR wouldn't be necessary, so I'm not sure what we're preserving here unless I've missed something in this PR that was broken before my bad commit.

**Comment by rodowi** [comment]
> Well, if I hadn't bungled the commit, this PR wouldn't be necessary

true, I'm closing this PR and opening a new one with just the revert action and applying only the lambda-cfn upgrade, makes sense?

**Comment by zmully** [comment]
:+1:

**Pull request closed without merging**
